# Generated by Django 5.0.2 on 2024-02-21 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='time',
        ),
        migrations.AddField(
            model_name='train',
            name='arr_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='train',
            name='dep_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='train',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
