# Generated by Django 5.0.2 on 2024-02-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0002_remove_train_time_train_arr_time_train_dep_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('class_type', models.CharField(max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='train_app.train')),
            ],
        ),
    ]
